/** Compiles contracts/Lens.sol with forge in a temp project and writes its runtime code to src/lens.ts. */
import { $ } from 'bun'
import { mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')
const dir = mkdtempSync(join(tmpdir(), 'lens-'))
await $`mkdir -p ${dir}/src && cp ${root}/contracts/Lens.sol ${dir}/src/`
await Bun.write(
  join(dir, 'foundry.toml'),
  '[profile.default]\nsrc="src"\nout="out"\noptimizer=true\noptimizer_runs=200\nevm_version="cancun"\nvia_ir=true\n',
)
await $`forge build --root ${dir}`.quiet()
const art = await Bun.file(join(dir, 'out/Lens.sol/Lens.json')).json()
await Bun.write(
  join(root, 'src/lens.ts'),
  `// Generated by \`bun run lens\` from contracts/Lens.sol. Do not edit.\nexport const LENS_CODE = '${art.deployedBytecode.object}'\n`,
)
console.log('wrote src/lens.ts', art.methodIdentifiers)
