/**
 * Halloween Remys art: `npm run halloween:art`
 *
 * Reads every minted Halloween Remy (Base, 0x5b8f…21cf) through tokenURI, fetches its
 * metadata and image from IPFS, and writes media/halloween/<id>.webp (1024×1024 WebP, the full-size source for the
 * halloween/<recipe>/<width>/<id>.webp variants in scripts/media.mjs). Existing files are kept, so reruns only
 * download new mints. Writes src/lib/halloweenIds.ts, the token ids the site may show. Then run `npm run media:sync`.
 */
import { existsSync } from 'node:fs'
import { mkdir, readdir, rename, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'
import { createPublicClient, http, parseAbi } from 'viem'
import { base } from 'viem/chains'

const ROOT = fileURLToPath(new URL('../', import.meta.url))
const OUT = join(ROOT, 'media/halloween')
const IDS_FILE = join(ROOT, 'src/lib/halloweenIds.ts')
const CONTRACT = '0x5b8fb8291cca09736c2720c76899be7debd321cf'
const MAX_SUPPLY = 666
const SIZE = 1024
const QUALITY = 86
const GATEWAYS = ['https://gateway.pinata.cloud/ipfs/', 'https://ipfs.filebase.io/ipfs/', 'https://ipfs.io/ipfs/', 'https://w3s.link/ipfs/']

const client = createPublicClient({ chain: base, transport: http(process.env.BASE_RPC ?? 'https://mainnet.base.org'), batch: { multicall: true } })
const abi = parseAbi(['function tokenURI(uint256) view returns (string)'])

async function ipfs(uri) {
  const path = uri.replace(/^ipfs:\/\//, '')
  let last
  for (let attempt = 0; attempt < 3; attempt++) {
    for (const gw of GATEWAYS) {
      try {
        const res = await fetch(gw + path, { headers: { 'user-agent': 'basedremyboys.club art sync' }, signal: AbortSignal.timeout(60_000) })
        if (res.ok) return Buffer.from(await res.arrayBuffer())
        last = new Error(`${gw}${path}: ${res.status}`)
      } catch (error) {
        last = error
      }
    }
    await new Promise((r) => setTimeout(r, 2000 * 2 ** attempt))
  }
  throw last
}

async function pool(items, limit, fn) {
  let next = 0
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      while (next < items.length) await fn(items[next++])
    }),
  )
}

const ids = Array.from({ length: MAX_SUPPLY }, (_, i) => i + 1)
const uris = await client.multicall({
  contracts: ids.map((id) => ({ address: CONTRACT, abi, functionName: 'tokenURI', args: [BigInt(id)] })),
  allowFailure: true,
})
const minted = ids.flatMap((id, i) => (uris[i].status === 'success' ? [{ id, uri: uris[i].result }] : []))
console.log(`${minted.length} Halloween Remys minted`)

await mkdir(OUT, { recursive: true })
const todo = minted.filter((m) => !existsSync(join(OUT, `${m.id}.webp`)))
let done = 0
const failed = []
await pool(todo, 3, async ({ id, uri }) => {
  try {
    const meta = JSON.parse((await ipfs(uri)).toString())
    const image = await ipfs(meta.image)
    const webp = await sharp(image).resize({ width: SIZE, height: SIZE, fit: 'cover' }).webp({ quality: QUALITY, effort: 6 }).toBuffer()
    const file = join(OUT, `${id}.webp`)
    await writeFile(`${file}.tmp`, webp)
    await rename(`${file}.tmp`, file)
  } catch (error) {
    failed.push(id)
    console.error(`#${id}: ${error.message ?? error}`)
  }
  if (++done % 20 === 0 || done === todo.length) console.log(`art ${done}/${todo.length}`)
})

const have = (await readdir(OUT))
  .filter((f) => /^\d+\.webp$/.test(f))
  .map((f) => Number.parseInt(f, 10))
  .sort((a, b) => a - b)
await writeFile(
  IDS_FILE,
  `// Generated by scripts/halloween-art.mjs: Halloween Remys with art in media/halloween.\nexport const HALLOWEEN_IDS: readonly number[] = [${have.join(', ')}]\n`,
)
console.log(`${have.length} Halloween Remys in media/halloween${failed.length ? `; failed: ${failed.join(', ')} (rerun to retry)` : ''}`)
